postgres_default: &postgres_default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { ENV.fetch("RAILS_MAX_THREADS") { 5 } } %>
  prepared_statements: false

development:
  primary:
    <<: *postgres_default
    database: cocoscout_development
    host: localhost
  cache:
    <<: *postgres_default
    database: cocoscout_development
    host: localhost
    migrations_paths: db/cache_migrate
  queue:
    <<: *postgres_default
    database: cocoscout_development
    host: localhost
    migrations_paths: db/queue_migrate
  cable:
    <<: *postgres_default
    database: cocoscout_development
    host: localhost
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *postgres_default
    database: cocoscout_test
    host: localhost
  cache:
    <<: *postgres_default
    database: cocoscout_test
    host: localhost
    migrations_paths: db/cache_migrate
  queue:
    <<: *postgres_default
    database: cocoscout_test
    host: localhost
    migrations_paths: db/queue_migrate
  cable:
    <<: *postgres_default
    database: cocoscout_test
    host: localhost
    migrations_paths: db/cable_migrate

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("DB_POOL") { ENV.fetch("RAILS_MAX_THREADS") { 5 } } %>
    prepared_statements: false
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *postgres_default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *postgres_default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *postgres_default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate