default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/development.sqlite3
  queue:
    <<: *default
    database: storage/development.sqlite3
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: db/test.sqlite3
  queue:
    <<: *default
    database: storage/test.sqlite3
    migrations_paths: db/queue_migrate

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("DB_POOL") { ENV.fetch("RAILS_MAX_THREADS") { 5 } } %>
    prepared_statements: false
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    database: db/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: db/production_queue.sqlite3
    migrations_paths: db/queue_migrate