default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

postgres_default: &postgres_default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { ENV.fetch("RAILS_MAX_THREADS") { 5 } } %>
  prepared_statements: false

development:
  primary:
    <<: *postgres_default
    database: cocoscout_development
    host: localhost
  cache:
    <<: *default
    database: db/development_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/development.sqlite3
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *postgres_default
    database: cocoscout_test
    host: localhost
  queue:
    <<: *default
    database: storage/test.sqlite3
    migrations_paths: db/queue_migrate

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("DB_POOL") { ENV.fetch("RAILS_MAX_THREADS") { 5 } } %>
    prepared_statements: false
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    database: db/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: db/production_queue.sqlite3
    migrations_paths: db/queue_migrate